# Generated by Django 6.0.3 on 2026-04-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
    ]
