# Generated by Django 5.2.8 on 2026-05-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0002_userprofile_avatar_alter_article_id_alter_comment_id_and_more'),
        ('platform_app', '0005_alter_userprofile_avatar'),
    ]

    operations = [
    ]
